name: ci

on:
  push:
    branches: 
      - main
      - feature-actions

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Log Env Vars
        run: echo $EVENT_NAME
        env:
          EVENT_NAME: ${{ github.event_name }}
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:edge
            ${{ github.repository }}:${{ steps.date.outputs.date }}