name: pr

on:
  pull_request:

jobs:
  go-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  go-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-test
        run: go test -v -coverprofile=profile.cov ./... | tee > test-output
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-output
          path: test-output
